"""Create players table

Revision ID: fee129eae2ac
Revises: 
Create Date: 2025-04-18 09:54:15.701685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee129eae2ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('college', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('ppg', sa.Float(), nullable=True),
    sa.Column('apg', sa.Float(), nullable=True),
    sa.Column('rpg', sa.Float(), nullable=True),
    sa.Column('spg', sa.Float(), nullable=True),
    sa.Column('bpg', sa.Float(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('threept_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
